/**
 * R3 (#119/#120/#121/#127/#128/#129/#130) — the barrel-surface characterization pin.
 *
 * R3 is **pure code motion**: symbols move between modules but the public surface
 * of the core barrel (`src/core/index.ts`) must not silently change. A split may
 * only **ADD** names (a new free function like `deepRest`, a new helper like
 * `registerEvent`); an alias deletion **REMOVES** a named symbol; a rename is an
 * add + a remove. Each such delta must be **intentional and reviewed** — this test
 * freezes the sorted runtime export-name list so any unplanned change to the
 * surface fails loudly, by name.
 *
 * When this test fails: confirm the delta is exactly what the current increment
 * intends (the commit body names it), then update `EXPECTED_BARREL_SURFACE`
 * in the same commit.
 *
 * Note: this pins the **runtime** exports (values, functions, classes, consts) via
 * `Object.keys` — type-only re-exports do not appear here (a type rename is
 * compiler-enforced elsewhere). Pure logic: no Phaser, no DOM.
 *
 * Recorded at increment 0 (2026-07-09): 615 names, sim digest byte-identical to
 * the reference in `r2-verb-gate.test.ts`'s header (1050 tests / 98 files green).
 *
 * Deltas:
 *   - increment 1 (#128 part A): −5 dead aliases removed — `grantCombatXp`,
 *     `scout`, `seerDivine`, `useCampJobSkill`, `useCampSkillAtNode` (→ 610).
 *   - increment 2 (#119, node-events split): +3 — `emptyOutcome` and
 *     `INFLUENCE_ORDER` exported from node-events for the new sibling modules
 *     (`stories.ts`, `early-events.ts`, `hollow-mill-events.ts`), and
 *     `HOLLOW_MILL_EVENTS` (the authored-record array registered via
 *     `registerEvent`). The moved story/early-event symbols keep the same barrel
 *     names, just new module homes (→ 613).
 *   - increment 3 (#120, recovery extraction): +2 — `deepRest` and `inPlaceRest`
 *     free functions in the new `recovery.ts` (the recovery economy lifted out of
 *     `RunLoop`); `REST` moved from runloop.ts to recovery.ts, same barrel name (→ 615).
 *   - increment 4 (#129, overworld-actions split): net 0 — the state API moved to
 *     `overworld-state.ts`, the cost grammar + gate + validator to `overworld-cost.ts`,
 *     and `triage`/`TRIAGE`/`TRIAGE_COST`/`isHealer` to `economy-actions.ts` beside the
 *     other economy verbs; every symbol keeps its barrel name at its new home (615).
 *   - increment 5 (#130, jobs split): net 0 — the combat roster moved to
 *     `jobs-data/combat.ts`, the Scout prestige line to `jobs-data/scout-line.ts`,
 *     and the support/economy classes + universal skills to `jobs-data/support.ts`;
 *     `jobs.ts` keeps the engine (`JOBS`/`SKILLS`/capabilities). Every symbol keeps
 *     its barrel name at its new home (615).
 *   - increment 6 (#121, turn split): net 0 — the undo substrate moved to
 *     `battle-undo.ts` (`snapshotUnit`/`restoreUnit` + the checkpoint machinery),
 *     the replay driver + `planActions` to `battle-replay.ts`, and the roster-aware
 *     resolvers to `field-effects.ts`. `Battle` stays in `turn.ts`, which re-exports
 *     `snapshotUnit`/`restoreUnit`/`replay` so the public surface is unchanged; the
 *     new modules' internal helpers (`captureCheckpoint`, `planActions`,
 *     `resolveShove`, …) are not surfaced (615).
 *   - increment 7 (#127, predicate-on-node seam): +1 — `evalPredicateRun`, the
 *     unit-less `grants.ts` evaluator `run.ts`'s `nodeAccessible` reads the new
 *     `MapNode.blockedWhen` access data through. The `securedWagon × medic-freed`
 *     rule is now authored data in `hollow-mill.ts`; the `flagSet` Predicate leaf +
 *     `blockedWhen` field are type-only (not runtime surface) (→ 616).
 *   - increment 8 (#128 part B, renames): net 0 — the ten bare job constants
 *     unify on the `*_JOB` convention: `SOLDIER`→`SOLDIER_JOB`,
 *     `HEAVY_KNIGHT`→`HEAVY_KNIGHT_JOB`, `HUNTER`→`HUNTER_JOB`,
 *     `MEDIC`→`MEDIC_JOB`, `SNARE_TRAPPER`→`SNARE_TRAPPER_JOB`,
 *     `COOK`→`COOK_JOB`, `MERCHANT`→`MERCHANT_JOB`, `NOBLE`→`NOBLE_JOB`,
 *     `BANKER`→`BANKER_JOB`, `SURVIVALIST`→`SURVIVALIST_JOB` (−10 +10). The other
 *     renames are not runtime-surface: `events.ts`→`event-bus.ts` (module file;
 *     `EventBus` etc. keep their names), `EncounterRecord`→`NightRecord` and
 *     `OverworldEconomy`→`OverworldState` (types), `Battle.runEnemyTurn`→
 *     `runPolicyTurn` (a method). Still 616.
 */
import { describe, it, expect } from "vitest";
import * as barrel from "./index";

// The sorted runtime export-name list of the core barrel. Update ONLY with an
// intentional, commit-documented delta (see the header). Increment-0 baseline.
const EXPECTED_BARREL_SURFACE: readonly string[] = [
  "ACT_COST",
  "AI",
  "ASSASSIN_JOB",
  "BANDIT_TEMPLATES",
  "BANKER_BORROW_COST",
  "BANKER_INTEREST_COST",
  "BANKER_JOB",
  "BANKER_PROTECT_COST",
  "BLOCKADE",
  "BROTHER",
  "BYPASS",
  "Battle",
  "CAPABILITY_PREDICATES",
  "CHANNEL_TUNING",
  "CHARGE_THRESHOLD",
  "CHUNK_FRACTION",
  "CLERIC_COST",
  "CLOCK_GUARD_MAX",
  "CLOCK_URGENT_NIGHTS",
  "COOK_JOB",
  "COOK_KIT",
  "COOK_STEW",
  "CORE_INVARIANTS",
  "CRITICAL_HP_FRACTION",
  "CTClock",
  "DASH_CAPTURE_FACTOR",
  "DEAL_PRIMED_FLAG",
  "DEFAULT_GOAL",
  "DEFAULT_MAX_NODES",
  "DEFAULT_MAX_ROUTES",
  "DEFAULT_MAX_SAMPLES",
  "DEFAULT_POLICIES",
  "DEFAULT_SCORE_WEIGHTS",
  "DEFAULT_SEED_SALTS",
  "DEFEND",
  "DEFT_HANDS",
  "DIFFICULTIES",
  "DIG_IN",
  "DIG_IN_CAPTURE_FACTOR",
  "DYING_COUNTER",
  "E1_SKIRMISH",
  "EARLY_EVENT",
  "ECONOMY",
  "ENEMY_TEMPLATES",
  "EQUIPMENT",
  "EQUIP_DECAY_PER_WEAR",
  "EVENTS",
  "EXPOSED",
  "EntityRegistry",
  "EventBus",
  "FATIGUE",
  "FATIGUE_TIER_FLOORS",
  "FEAST",
  "FIND_TRADE",
  "FLANK",
  "FORAGE",
  "FORAGE_KIT",
  "FRONT_ADVANCE_PER_TURN",
  "FRONT_DANGER",
  "FRONT_SPEED_LEAN",
  "GEAR_CONDITION",
  "GEAR_WEAR_WARN",
  "GEN",
  "GUARDED",
  "GUILD",
  "HASTENED",
  "HEAVY_KNIGHT_JOB",
  "HOLLOW_MILL_EVENTS",
  "HOLLOW_MILL_PARTY",
  "HUNTER_JOB",
  "IMMOBILIZED",
  "INFLUENCE_BANDS",
  "INFLUENCE_ORDER",
  "INTEL_BREAKPOINTS",
  "JOBS",
  "KIT",
  "LEVELING",
  "Labels",
  "MAIN_STATS",
  "MAP_GEN",
  "MARKED",
  "MARKET_TIERS",
  "MATERIALS",
  "MAX_TIER",
  "MEDIC_JOB",
  "MED_HEAL",
  "MERCHANT_BUY_COST",
  "MERCHANT_JOB",
  "MERCHANT_KIT",
  "MERCHANT_SELL_COST",
  "MIRA_MERCHANT",
  "MORALE_TIERS",
  "MORTALITY",
  "MOVE_COST",
  "NEUTRAL_DANGER",
  "NOBLE_JOB",
  "NODE_EVENTS",
  "ORTHO_OFFSETS",
  "PASSIVE",
  "PASSIVE_INFO",
  "PATRONIZE_COST",
  "PILOT_POLICY",
  "PIP_COOK",
  "PRESTIGE_OFFERS",
  "PRISON_WAGON",
  "PROTECT_MAP_DIVISOR",
  "QUIET_FOOTSTEPS_CAPTURE_FACTOR",
  "REACH",
  "RECON",
  "RECOVERY",
  "RECRUIT",
  "REST",
  "REWARD_BANDS",
  "REWARD_TABLE",
  "Rng",
  "RunLoop",
  "SAFE_BASE_RADIUS",
  "SAFE_POWER_PER_STEP",
  "SAVVY_BARTER",
  "SCOUT_JOB",
  "SCOUT_PRESTIGE_FLOOR",
  "SECURED_WAGON",
  "SELA_MEDIC",
  "SKILLS",
  "SLOWED",
  "SNARE_TRAPPER_JOB",
  "SOLDIER_JOB",
  "SPOT",
  "STANDING_ORDERS",
  "STATUS_TUNING",
  "STATUS_VISUALS",
  "STAT_KEYS",
  "STEALTH",
  "STEP_SPOT",
  "STOCK_ITEMS",
  "STORIES",
  "STUB_FINALE",
  "SUBTLE_BLADE_BONUS",
  "SURVEY",
  "SURVIVALIST_JOB",
  "SWIFT",
  "THEFT",
  "THE_HOLLOW_MILL",
  "THIEF_JOB",
  "THIEVES_DEN",
  "TILE_HEIGHT",
  "TILE_WIDTH",
  "TRAP_FIELD",
  "TRAP_INTEL",
  "TRIAGE",
  "TRIAGE_COST",
  "TURN_THRESHOLD",
  "TileGrid",
  "UNIVERSAL_SKILLS",
  "UPKEEP",
  "VERB_COSTS",
  "VESSELS",
  "abilityFootprint",
  "abilityScaleBonus",
  "accrueDeclaredFaucets",
  "accrueDeployedXp",
  "accruePurseInterest",
  "accrueRp",
  "activeRoster",
  "activeUnits",
  "addDelta",
  "addInfluence",
  "addItem",
  "adjacentBodies",
  "adjacentRevealedTrap",
  "advanceFront",
  "advanceOutcome",
  "aggregate",
  "aimInRange",
  "analyzeExpedition",
  "applyCampSkill",
  "applyCampToParty",
  "applyCharacterBoons",
  "applyDamage",
  "applyGearCondition",
  "applyGrant",
  "applyGrantEffect",
  "applyHeal",
  "applyJobLevelGains",
  "applyOverworldEffect",
  "applyProvisionChoice",
  "applyStatDelta",
  "applyStatus",
  "applyStoryChoice",
  "applyTownVisit",
  "armObjectives",
  "armSkillCooldown",
  "arrivalDigest",
  "assertNever",
  "assignMember",
  "attentionCount",
  "autoTrim",
  "availableGear",
  "availableRoster",
  "availableSkills",
  "bandFor",
  "bankerBorrow",
  "bankerBorrowPreview",
  "bankerEngageInterest",
  "bankerInterestPreview",
  "bankerProtect",
  "bankerProtectPreview",
  "batchSimulate",
  "battleOutcome",
  "breakCamp",
  "bribeChance",
  "bribeCost",
  "bribeEnemy",
  "buildAuthoredCaptives",
  "buildAuthoredEnemies",
  "buildAuthoredGrid",
  "buildEnemies",
  "buildGrid",
  "buildLedger",
  "bumpCounter",
  "byReadiest",
  "bypassFee",
  "bypassXp",
  "campChipLine",
  "campReadout",
  "campReadoutLine",
  "campSkillUses",
  "campSkillUsesLeft",
  "campfireRadius",
  "canAdd",
  "canAffordInfluence",
  "canDisarm",
  "canPlacePlayerTrap",
  "canSee",
  "canSeeUnit",
  "captainsJournal",
  "captureChanceAt",
  "captureEvasionFactor",
  "captureUnit",
  "caravanCapacity",
  "chebyshev",
  "checkOverworldCost",
  "chooseEventOption",
  "chooseNode",
  "chunkHp",
  "clamp",
  "clamp01",
  "clampTier",
  "clampUp",
  "clampUpMarket",
  "cleanseOne",
  "cleaveArc",
  "clericRevive",
  "cloneOverworldEconomy",
  "combatRoster",
  "commitCombatXp",
  "commitsTurn",
  "committedGearIds",
  "committedMemberIds",
  "computeDamage",
  "computeFlankBonus",
  "computeUpkeep",
  "computeVisibleTiles",
  "configureDeployClock",
  "consumeFlag",
  "cooldownRemaining",
  "countOf",
  "createCamp",
  "createCampfire",
  "createCaravan",
  "createDeployClock",
  "createFront",
  "createGuild",
  "createInventory",
  "createOverworldEconomy",
  "createPlaytestLog",
  "createRun",
  "createRunFromCaravan",
  "createRunFromExpedition",
  "createUnit",
  "currentEncounter",
  "currentNode",
  "debuffs",
  "decayCounters",
  "declaredFaucetInfluence",
  "deepRest",
  "deftHandsSkim",
  "degradedMods",
  "deployActions",
  "deployForecast",
  "describeUnit",
  "disarmTrap",
  "dispatch",
  "dispatchRefusal",
  "earlyEventForNode",
  "earn",
  "edgeDistance",
  "effectiveIntelTier",
  "effectiveMarketTier",
  "effectiveMove",
  "effectiveSpeed",
  "eligibleGrants",
  "eligiblePrestiges",
  "emptyOutcome",
  "encounterOutcome",
  "enemyCount",
  "enumerateCompletions",
  "enumeratePaths",
  "equip",
  "equipDelta",
  "equipModsSummary",
  "equippedIds",
  "evalPredicate",
  "evalPredicateRun",
  "eventChoices",
  "eventForNode",
  "eventWeightAt",
  "exhaustionSlowSpeed",
  "exposed",
  "fatigueRisk",
  "fatigueTier",
  "fatigueTierIndex",
  "fieldedUnits",
  "fieldsJob",
  "findPath",
  "flankTiles",
  "foodFirst",
  "forecastAttack",
  "forecastEnemyAction",
  "forecastSkill",
  "forget",
  "formatDigest",
  "freeCaptive",
  "frontCaptureChance",
  "frontSpeed",
  "frontTurnStage",
  "gainRunGold",
  "gearDelta",
  "gearRefusal",
  "generateEncounter",
  "generateOverworld",
  "getCounter",
  "getDifficulty",
  "getEnemyTemplate",
  "getEquipment",
  "getEvent",
  "getExpedition",
  "getJob",
  "getMaterial",
  "getNode",
  "getQuest",
  "getSkill",
  "getStory",
  "getVessel",
  "grantAbilityUseXp",
  "grantItem",
  "grantJobXp",
  "grantXp",
  "gridToScreen",
  "guarded",
  "hasActive",
  "hasBanker",
  "hasConcerns",
  "hasGear",
  "hasMember",
  "hasNoble",
  "hasNodeFlag",
  "hasPacing",
  "hasPrice",
  "hasStatus",
  "hasThief",
  "hashSeed",
  "hastened",
  "healAmount",
  "healUnit",
  "hiddenTraps",
  "hireFromPool",
  "hireMercenary",
  "hireRecruit",
  "hireRefusal",
  "immobilized",
  "inAttackRange",
  "inDangerZone",
  "inFlightCaravans",
  "inPlaceRest",
  "inPlaceRestPreview",
  "inSafeZone",
  "incrementCounter",
  "influenceTier",
  "intelDeployBonus",
  "intelDepthOf",
  "intelFloor",
  "isActive",
  "isAdjacent",
  "isAuthoredEncounter",
  "isCaptured",
  "isConcealedTrap",
  "isDebuffed",
  "isDying",
  "isExhausted",
  "isFatigueTier0",
  "isFinalNode",
  "isFinalRunNode",
  "isFlanked",
  "isHealer",
  "isImmobilized",
  "isNodeVisible",
  "isOverworldActionEffect",
  "isPrimed",
  "isProtected",
  "isRecoverable",
  "isRunComplete",
  "isRunOver",
  "isStealthed",
  "isValidSkillTarget",
  "itemEffect",
  "jeopardyOf",
  "jobLevelOf",
  "jobPresenceSummary",
  "knobDeclared",
  "loadPurse",
  "loadSupply",
  "lockGear",
  "lootBandFor",
  "makeConcealedTrap",
  "makeTrap",
  "manhattan",
  "markBonus",
  "markOf",
  "markPrey",
  "marketOpenedFlag",
  "marketRank",
  "marketTierBonus",
  "medHealAmount",
  "memberRefusal",
  "mercPool",
  "merchantBuy",
  "merchantPrice",
  "merchantSell",
  "moraleModifiers",
  "moraleTier",
  "moraleTierIndex",
  "moveBudget",
  "nightEndGate",
  "nightlyFatigue",
  "noActionsAvailable",
  "nodeAccessible",
  "nodeEncounter",
  "nodeFee",
  "nonNegInt",
  "nudgeMorale",
  "occupiedGrid",
  "onSkillCooldown",
  "openingPurseLog",
  "opposite",
  "orderOf",
  "orthoNeighbors",
  "overworldCostOf",
  "partyPresence",
  "patronize",
  "patronizePreview",
  "payTreasuryUpkeep",
  "payUpkeep",
  "pickRepresentatives",
  "placeParty",
  "placePlayerTrap",
  "placePlayersAutoEdge",
  "planAttack",
  "planEnemyTurn",
  "planMove",
  "playToTerminal",
  "prestige",
  "prestigeOptions",
  "previewNode",
  "primaryJobOf",
  "primeFlag",
  "projectDossier",
  "projectForecast",
  "projectManifest",
  "protectRadiusOn",
  "purseFromLog",
  "purseTotalBySource",
  "rampMark",
  "rankOf",
  "reachLimit",
  "reachableFrom",
  "reachableNodes",
  "reachableTiles",
  "readEncounter",
  "recall",
  "recalls",
  "recordCamp",
  "recordEncounter",
  "recordEventNode",
  "recordInPlaceRest",
  "recordNight",
  "recordRestNode",
  "recoverMaterials",
  "recoverStolen",
  "recruitClassify",
  "recruitToRoster",
  "recruiterOffer",
  "refillBoard",
  "refreshAuras",
  "refreshMercPool",
  "registerExpedition",
  "remember",
  "removeFromRoster",
  "removeItem",
  "removeStatus",
  "replay",
  "resetCaravan",
  "resolveAttack",
  "resolveCaptured",
  "resolveDowned",
  "resolveEarlyEvent",
  "resolveEvent",
  "resolveFrontTurn",
  "resolveKnob",
  "resolveMedHeal",
  "resolveReturn",
  "resolveSkill",
  "restCostMultiplier",
  "restHeal",
  "restoreFatigue",
  "restoreUnit",
  "retaliationDamage",
  "revealTrapsNear",
  "revertGearStamp",
  "revertStatDelta",
  "rewardBand",
  "rewardHint",
  "rollMercenary",
  "rollSkim",
  "routeCombatXp",
  "routePayoutToTreasury",
  "rpPerNight",
  "runDifficulty",
  "runEncounter",
  "runFor",
  "safeGroundRemains",
  "saleValueOf",
  "samplePopulation",
  "satisfyUpkeepLine",
  "scoreArrival",
  "scoutedTier",
  "screenToGrid",
  "sellPrice",
  "setCounter",
  "setNodeFlag",
  "shopBuy",
  "shopStock",
  "shoveLanding",
  "sideSeed",
  "simulateRun",
  "skillContexts",
  "skillEffectPreview",
  "skillsUnlockedBetween",
  "slotsFor",
  "slotsFree",
  "slotsOver",
  "slotsRemaining",
  "slotsUsed",
  "slowed",
  "snapshot",
  "snapshotRun",
  "snapshotUnit",
  "spend",
  "spendFatigue",
  "spendInfluence",
  "spendRp",
  "spotChance",
  "spotRadius",
  "spotWhileMoving",
  "stageEncounter",
  "stampPassives",
  "statusAmount",
  "statusVisual",
  "stealth",
  "stepDistance",
  "storyChoices",
  "storyForNode",
  "streamFor",
  "summarizePlaytest",
  "swift",
  "tailoredEarlyEventFor",
  "thiefEscapes",
  "thiefEventSkim",
  "thiefSteal",
  "threatenedTiles",
  "tickCooldowns",
  "tickDyingClocks",
  "tickSkillCooldowns",
  "tickStatuses",
  "tickUntilReady",
  "tileKey",
  "tollFee",
  "trackCombatXp",
  "traverseRoute",
  "triage",
  "triageActionPreview",
  "triageHealAmount",
  "unassignMember",
  "unequip",
  "unitAbilityRows",
  "unitHasCapability",
  "unitPresence",
  "unitSkills",
  "unlockGear",
  "unlockedSkills",
  "useOverworldSkill",
  "validateExpedition",
  "validateOverworldCost",
  "visibleNodes",
  "withDefaultGoal",
  "woundedBySeverity",
];

describe("R3 barrel surface — the core public export names are frozen (pure motion)", () => {
  it("exposes exactly the expected sorted runtime export names", () => {
    const actual = Object.keys(barrel).sort();
    expect(actual).toEqual([...EXPECTED_BARREL_SURFACE]);
  });

  it("has no duplicate export names", () => {
    const names = Object.keys(barrel);
    expect(names.length).toBe(new Set(names).size);
  });
});
