/**
 * R3 (#119/#120/#121/#127/#128/#129/#130) — the barrel-surface characterization pin.
 *
 * R3 is **pure code motion**: symbols move between modules but the public surface
 * of the core barrel (`src/core/index.ts`) must not silently change. A split may
 * only **ADD** names (a new free function like `deepRest`, a new helper like
 * `registerEvent`); an alias deletion **REMOVES** a named symbol; a rename is an
 * add + a remove. Each such delta must be **intentional and reviewed** — this test
 * freezes the sorted runtime export-name list so any unplanned change to the
 * surface fails loudly, by name.
 *
 * When this test fails: confirm the delta is exactly what the current increment
 * intends (the commit body names it), then update `EXPECTED_BARREL_SURFACE`
 * in the same commit.
 *
 * Note: this pins the **runtime** exports (values, functions, classes, consts) via
 * `Object.keys` — type-only re-exports do not appear here (a type rename is
 * compiler-enforced elsewhere). Pure logic: no Phaser, no DOM.
 *
 * Recorded at increment 0 (2026-07-09): 615 names, sim digest byte-identical to
 * the reference in `r2-verb-gate.test.ts`'s header (1050 tests / 98 files green).
 *
 * Deltas:
 *   - increment 1 (#128 part A): −5 dead aliases removed — `grantCombatXp`,
 *     `scout`, `seerDivine`, `useCampJobSkill`, `useCampSkillAtNode` (→ 610).
 *   - increment 2 (#119, node-events split): +3 — `emptyOutcome` and
 *     `INFLUENCE_ORDER` exported from node-events for the new sibling modules
 *     (`stories.ts`, `early-events.ts`, `hollow-mill-events.ts`), and
 *     `HOLLOW_MILL_EVENTS` (the authored-record array registered via
 *     `registerEvent`). The moved story/early-event symbols keep the same barrel
 *     names, just new module homes (→ 613).
 *   - increment 3 (#120, recovery extraction): +2 — `deepRest` and `inPlaceRest`
 *     free functions in the new `recovery.ts` (the recovery economy lifted out of
 *     `RunLoop`); `REST` moved from runloop.ts to recovery.ts, same barrel name (→ 615).
 *   - increment 4 (#129, overworld-actions split): net 0 — the state API moved to
 *     `overworld-state.ts`, the cost grammar + gate + validator to `overworld-cost.ts`,
 *     and `triage`/`TRIAGE`/`TRIAGE_COST`/`isHealer` to `economy-actions.ts` beside the
 *     other economy verbs; every symbol keeps its barrel name at its new home (615).
 *   - increment 5 (#130, jobs split): net 0 — the combat roster moved to
 *     `jobs-data/combat.ts`, the Scout prestige line to `jobs-data/scout-line.ts`,
 *     and the support/economy classes + universal skills to `jobs-data/support.ts`;
 *     `jobs.ts` keeps the engine (`JOBS`/`SKILLS`/capabilities). Every symbol keeps
 *     its barrel name at its new home (615).
 *   - increment 6 (#121, turn split): net 0 — the undo substrate moved to
 *     `battle-undo.ts` (`snapshotUnit`/`restoreUnit` + the checkpoint machinery),
 *     the replay driver + `planActions` to `battle-replay.ts`, and the roster-aware
 *     resolvers to `field-effects.ts`. `Battle` stays in `turn.ts`, which re-exports
 *     `snapshotUnit`/`restoreUnit`/`replay` so the public surface is unchanged; the
 *     new modules' internal helpers (`captureCheckpoint`, `planActions`,
 *     `resolveShove`, …) are not surfaced (615).
 *   - increment 7 (#127, predicate-on-node seam): +1 — `evalPredicateRun`, the
 *     unit-less `grants.ts` evaluator `run.ts`'s `nodeAccessible` reads the new
 *     `MapNode.blockedWhen` access data through. The `securedWagon × medic-freed`
 *     rule is now authored data in `hollow-mill.ts`; the `flagSet` Predicate leaf +
 *     `blockedWhen` field are type-only (not runtime surface) (→ 616).
 *   - increment 8 (#128 part B, renames): net 0 — the ten bare job constants
 *     unify on the `*_JOB` convention: `SOLDIER`→`SOLDIER_JOB`,
 *     `HEAVY_KNIGHT`→`HEAVY_KNIGHT_JOB`, `HUNTER`→`HUNTER_JOB`,
 *     `MEDIC`→`MEDIC_JOB`, `SNARE_TRAPPER`→`SNARE_TRAPPER_JOB`,
 *     `COOK`→`COOK_JOB`, `MERCHANT`→`MERCHANT_JOB`, `NOBLE`→`NOBLE_JOB`,
 *     `BANKER`→`BANKER_JOB`, `SURVIVALIST`→`SURVIVALIST_JOB` (−10 +10). The other
 *     renames are not runtime-surface: `events.ts`→`event-bus.ts` (module file;
 *     `EventBus` etc. keep their names), `EncounterRecord`→`NightRecord` and
 *     `OverworldEconomy`→`OverworldState` (types), `Battle.runEnemyTurn`→
 *     `runPolicyTurn` (a method). Still 616.
 *   - increment 9 (#128 part C, stranded helpers): net 0 — `describeUnit` (was in
 *     `node-events.ts`) and `jobPresenceSummary` (was in `jobs.ts`) move to
 *     `dossier.ts` beside the other read-only projections; both keep their barrel
 *     names at the new home (616).
 *
 * R4 batch-1 deltas (#113 — the cost grammar):
 *   - increment 3 (material prices): +1 — `canAffordMaterial` (inventory.ts), the core
 *     availability projection deriving a "0 herbs / 0 kits" greyed state from a skill's
 *     declared material price (→ 617). The `cost.ts` grammar (`Cost`/`CostPrice`/
 *     `ClockDomain`/`MaterialCost`) and the `SkillCost`/`OverworldCost` views are all
 *     type-only (not runtime surface).
 *   - increment 4 (#123 — SkillDef.phase retires): −1 — `unlockedSkills` deleted (its callers
 *     migrated to `availableSkills`, the one authoritative surfacing projection); `unitSkills`
 *     keeps its name (signature dropped the `phase` param). The `Phase` type is deleted too
 *
 * R4 batch-2 deltas (#112 — the economy-verb migration):
 *   - increment 5 (effect kinds + handlers): +10 — the post-gate effect **cores** each economy
 *     verb shares with the new `OVERWORLD_EFFECT_HANDLERS` entries (`applyBuyEffect`,
 *     `applySellEffect`, `applyBorrowEffect`, `applyEngageInterestEffect`, `applyGuardPurseEffect`,
 *     `applyPatronizeEffect`, `applyTriageEffect`, `applyTriageFallbackEffect`), the Triage target
 *     selector `mostWoundedFielded`, and the `buyPriceFor` Savvy-Barter price helper. The new
 *     `OverworldActionEffect` variants (sell/borrow/…/buy/triage) are type-only (not runtime).
 *   - increment 6 (Merchant sell + Banker verbs → SkillDefs): net 0 — +4 SkillDefs
 *     (`MERCHANT_SELL`, `BANKER_INTEREST`, `BANKER_BORROW`, `BANKER_GUARD` on their jobs),
 *     −4 dissolved cost consts (`MERCHANT_SELL_COST`, `BANKER_INTEREST_COST`,
 *     `BANKER_BORROW_COST`, `BANKER_PROTECT_COST` — their rows folded into the SkillDefs).
 *   - increment 7 (Noble patronize → SkillDef + bribe onto the Influence knob): net 0 —
 *     +1 `NOBLE_PATRONIZE` (on the Noble), −1 `PATRONIZE_COST` (row folded in). `bribeEnemy`
 *     keeps its name (its Influence spend now rides the shared gate's `influence` knob).
 *   - increment 8 (triage + universal buy): +6 −2 (net +4) — +`MEDIC_TRIAGE` (full-strength
 *     Triage on the Medic), +`UNIVERSAL_BUY` / +`TRIAGE_FALLBACK` / +`UNIVERSAL_OVERWORLD_SKILLS`
 *     (the universal overworld home), + the cost-provider bodies `merchantBuyGold` /
 *     `triageFallbackRp`; −`MERCHANT_BUY_COST` (→ `merchantBuyGold` fn) and −`TRIAGE_COST`
 *     (folded into `MEDIC_TRIAGE`). `VERB_COSTS` is now empty (retires in increment 9).
 *   - increment 9 (VERB_COSTS retires): −1 — the emptied `VERB_COSTS` registry is deleted along
 *     with its module-load walk; the D88 guard inverts to prove the absence of standalone verbs.
 *     (type-only, not runtime surface) (→ 616).
 *
 * Structural-audit delta (D114 — 2026-07-20): +1 — `saltSeed` (`rng.ts`), the one home for
 *   the `seed#label` child-seed join (battle salt, quest/recruit seeds); the four hand-rolled
 *   joins migrated onto it byte-identically. Sim digest unchanged.
 *
 * Scenario-harness deltas (#170 — the visual scenario harness):
 *   - increment 1 (buildScenarioRun + the registry): +7 — `buildScenarioRun` and
 *     `DEFAULT_SCENARIO_GOLD` (`scenario.ts`, the synthetic-one-node-run builder), the
 *     registry `SCENARIOS` / `getScenario` / `listScenarios` (`scenarios/index.ts`), and the
 *     first entry's data `PICK_THE_CELL` / `PICK_THE_CELL_ENCOUNTER` (`scenarios/pick-the-cell.ts`,
 *     the taste fixture promoted out of `taste-infiltration.test.ts`). `ScenarioConfig` is
 *     type-only (not runtime surface). No registration at import (R3), so the sim digest is
 *     unchanged.
 *
 * Wave-0 topology deltas (#168 — the back-half map):
 *   - PR-1 (the Thief mentor two-beat, C7): +2 — `THIEVES_GUILD_CONTACT` / `THIEVES_GUILD_RITE`
 *     (`stories.ts`): the shipped single `thieves-guild` offer (an inline `PRESTIGE_OFFERS`
 *     member, never a named export) splits into the arm-early contact + fire-later rite, now
 *     named so the pinned `guild-contact` / `guild-rite` surfacing events can bind them. The
 *     new `StoryOutcomeSpec.jobXp` field + `pinnedStoryEvent` helper are type-only / module-
 *     private (not runtime surface). No registration change to the seeded pool → sim digest
 *     unchanged.
 *   - PR-2 (the topology rewrite): +1 net — +`OUTER_YARD` / +`CUFFED_CELL` (the two new
 *     infiltration-arm encounters in `hollow-mill.ts`), −`SECURED_WAGON` (the Medic catch-up,
 *     deleted — no catch-up on the Thief arm, C8). `CAPTIVE_PRISONER` is module-private.
 *
 * Interactable gates deltas (D103 — the prison-break substrate):
 *   - gate core (Phase 1): +8 — `makeGate` / `openGate` / `openGateOnGrid` / `applyGatesToGrid` /
 *     `canLockpickGate` / `lockpickableGates` / `gatesOpenedByDeath` (`gates.ts`, the locked-tile
 *     enclosure + the lockpick/keyholder open interpreters), and `matchesTag` (promoted from
 *     module-private in `objectives.ts` so the keyholder lock reuses the one tag matcher). `Gate` /
 *     `GateLock` are type-only. `TileGrid.setWalkable` is a method, not a barrel export. No
 *     registration at import → sim digest unchanged.
 *   - gate wiring (Phase 2a): +1 — `buildAuthoredGates` (`authored.ts`, inflate the authored
 *     `gates` field into live `Gate`s at staging). `AuthoredGate` + the `openGate` action + the
 *     `gateOpened` event + `Battle.gates`/`openGate` are type-only / methods (not runtime surface).
 *   - gate render (Phase 2b): +3 — `MICRO_GATE_LOCKPICK` / `MICRO_GATE_KEYHOLDER` / `MICRO_SCENARIOS`
*     (`scenarios/micro.ts`, the micro-interaction gallery registered in `SCENARIOS` — D104). The
 *     `ICON.gate` glyph + the scene's Pick-Cell verb / markGates render are `game/` (not core surface).
 *     (The transient `JAILBREAK` / `JAILBREAK_ENCOUNTER` showcase this replaced was never merged.)
 *   - gate destructible (Phase 3): +5 — `isBreakable` / `canAttackGate` / `breakableGates` / `damageGate`
 *     (`gates.ts`, the door-durability interpreters) + `MICRO_GATE_DESTRUCTIBLE` (`scenarios/micro.ts`, the
 *     batter-a-door fixture). The `attackGate` action + the `gateDamaged` event + `Gate.hp`/`maxHp` +
 *     `Battle.attackGate` + the scene's Break-Gate verb are type-only / methods (not runtime surface).
 *   - gate AI target (Phase 3): +1 — `MICRO_GATE_ENEMY_BATTER` (`scenarios/micro.ts`, the walled-off-guard
 *     fixture). The `AIPlan.gateTarget` / `AIOptions.gates` / `AI.doorBreak` door-targeting seam is
 *     type-only / a weight (not runtime surface).
 *   - gate lever (Phase 3): +6 — `makeLever` / `lockGateOnGrid` / `canPullLever` / `pullableLevers`
 *     (`gates.ts`, the pull-switch seal) + `buildAuthoredLevers` (`authored.ts`) + `MICRO_LEVER_SEAL`
 *     (`scenarios/micro.ts`, the slam-a-door-shut fixture). `Lever` / `AuthoredLever` / the `pullLever`
 *     action / the `gateLocked` event / `Battle.pullLever` / the scene's Pull-Lever verb are type-only /
 *     methods (not runtime surface).
 *   - gate destroyed / remnant (D106): +2 — `destroyGateOnGrid` (`gates.ts`, the smash-to-a-permanent-
 *     passable-remnant terminal state — the lever can never re-seal it) + `MICRO_GATE_REMNANT`
 *     (`scenarios/micro.ts`, the destroy-then-fail-to-reseal fixture). `Gate.broken` + the
 *     `ICON.gateRemnant` glyph + the scene's remnant render are type-only / `game/` (not core surface).
 *   - gate re-seal keeps damage (D107): +1 — `MICRO_GATE_RESEAL` (`scenarios/micro.ts`, the batter →
 *     lever-open → lever-reseal render guard proving the HP readout persists, no top-up). The
 *     `lockGateOnGrid` durability change is a method-body edit (not a surface delta).
 *
 * Tag system deltas (D117 — the `hasTag` classification surface, M1):
 *   - M1 (tags.ts): +6 — `TAGS` / `getTag` / `hasTag` + the three tag-id constants `IN_COMBAT` /
 *     `NON_COMBATANT` / `GARRISON`. `TagDef` / `TagProvenance` / `TagContext` are type-only; the
 *     `deriveInCombat` / `canDamage` predicates are module-private. `Unit.tags` is a type-only
 *     field add (no runtime surface). No registration at import → sim digest unchanged.
 *   - M2a (combat-log.ts): +1 — `exchangedDamageSince` (the `in-combat` clause-1 window query).
 *     `CombatLogEntry` is type-only; `Battle.eventLog`/`tagContext` are methods; `BattleCheckpoint.
 *     eventLogLen` is a type-only field. The event log is derived/passive → sim digest unchanged.
 *   - M2b (gates.ts): +3 — `canKeyGate` / `keyableGates` / `gateActFor` (the living-keyholder Act's
 *     validation + the key-vs-batter selector). `GateAct` + the `keyGate` `CombatAction` are type-only;
 *     `Battle.keyGate` is a method. No new registration/RNG → sim digest unchanged.
 *   - M2c (gates.ts): +1 — `keyholderOf` (position-independent keyholder match; the AI key-drive filter).
 *     `AIPlan.gateAct` is a type-only field; the planner reorder is behavior. No new registration/RNG.
 */
import { describe, it, expect } from "vitest";
import * as barrel from "./index";

// The sorted runtime export-name list of the core barrel. Update ONLY with an
// intentional, commit-documented delta (see the header). Increment-0 baseline.
const EXPECTED_BARREL_SURFACE: readonly string[] = [
  "ACT_COST",
  "AI",
  "ASSASSIN_JOB",
  "BANDIT_TEMPLATES",
  "BANKER_BORROW",
  "BANKER_GUARD",
  "BANKER_INTEREST",
  "BANKER_JOB",
  "BLOCKADE",
  "BROTHER",
  "BYPASS",
  "Battle",
  "CAPABILITY_PREDICATES",
  "CHANNEL_TUNING",
  "CHARGE_THRESHOLD",
  "CHUNK_FRACTION",
  "CLERIC_COST",
  "CLOCK_GUARD_MAX",
  "CLOCK_URGENT_NIGHTS",
  "COOK_JOB",
  "COOK_KIT",
  "COOK_STEW",
  "CORE_INVARIANTS",
  "CRITICAL_HP_FRACTION",
  "CTClock",
  "CUFFED_CELL",
  "DASH_CAPTURE_FACTOR",
  "DEAL_PRIMED_FLAG",
  "DEFAULT_GOAL",
  "DEFAULT_MAX_NODES",
  "DEFAULT_MAX_ROUTES",
  "DEFAULT_MAX_SAMPLES",
  "DEFAULT_POLICIES",
  "DEFAULT_SCENARIO_GOLD",
  "DEFAULT_SCORE_WEIGHTS",
  "DEFAULT_SEED_SALTS",
  "DEFEND",
  "DEFT_HANDS",
  "DIFFICULTIES",
  "DIG_IN",
  "DIG_IN_CAPTURE_FACTOR",
  "DYING_COUNTER",
  "E1_SKIRMISH",
  "EARLY_EVENT",
  "ECONOMY",
  "ENEMY_TEMPLATES",
  "EQUIPMENT",
  "EQUIP_DECAY_PER_WEAR",
  "EVENTS",
  "EXPOSED",
  "EntityRegistry",
  "EventBus",
  "FATIGUE",
  "FATIGUE_TIER_FLOORS",
  "FEAST",
  "FIND_TRADE",
  "FLANK",
  "FORAGE",
  "FORAGE_KIT",
  "FRONT_ADVANCE_PER_TURN",
  "FRONT_DANGER",
  "FRONT_SPEED_LEAN",
  "GARRISON",
  "GEAR_CONDITION",
  "GEAR_WEAR_WARN",
  "GEN",
  "GOAL_KINDS",
  "GUARDED",
  "GUILD",
  "HASTENED",
  "HEAVY_KNIGHT_JOB",
  "HOLLOW_MILL_EVENTS",
  "HOLLOW_MILL_PARTY",
  "HUNTER_JOB",
  "IMMOBILIZED",
  "INFLUENCE_BANDS",
  "INFLUENCE_ORDER",
  "INTEL_BREAKPOINTS",
  "IN_COMBAT",
  "JOBS",
  "KIT",
  "LEVELING",
  "Labels",
  "MAIN_STATS",
  "MAP_GEN",
  "MARKED",
  "MARKET_TIERS",
  "MATERIALS",
  "MAX_TIER",
  "MEDIC_JOB",
  "MEDIC_TRIAGE",
  "MED_HEAL",
  "MERCHANT_JOB",
  "MERCHANT_KIT",
  "MERCHANT_SELL",
  "MICRO_GATE_DESTRUCTIBLE",
  "MICRO_GATE_ENEMY_BATTER",
  "MICRO_GATE_KEYHOLDER",
  "MICRO_GATE_LOCKPICK",
  "MICRO_GATE_REMNANT",
  "MICRO_GATE_RESEAL",
  "MICRO_LEVER_SEAL",
  "MICRO_SCENARIOS",
  "MIRA_MERCHANT",
  "MORALE_TIERS",
  "MORTALITY",
  "MOVE_COST",
  "NEUTRAL_DANGER",
  "NOBLE_JOB",
  "NOBLE_PATRONIZE",
  "NODE_EVENTS",
  "NON_COMBATANT",
  "OBJECTIVE_KINDS",
  "ORTHO_OFFSETS",
  "OUTER_YARD",
  "PASSIVE",
  "PASSIVE_INFO",
  "PICK_THE_CELL",
  "PICK_THE_CELL_ENCOUNTER",
  "PILOT_POLICY",
  "PIP_COOK",
  "PRESTIGE_OFFERS",
  "PRISON_ASSAULT",
  "PRISON_ASSAULT_SCENARIO",
  "PRISON_ASSAULT_SCENARIO_ENCOUNTER",
  "PRISON_WAGON",
  "PROTECT_MAP_DIVISOR",
  "QUIET_FOOTSTEPS_CAPTURE_FACTOR",
  "REACH",
  "RECON",
  "RECOVERY",
  "RECRUIT",
  "REPRO_DUMP_VERSION",
  "RESCUE_FINALE_ID",
  "RESCUE_PARTY",
  "REST",
  "REWARD_BANDS",
  "REWARD_TABLE",
  "Rng",
  "RunLoop",
  "SAFE_BASE_RADIUS",
  "SAFE_POWER_PER_STEP",
  "SAVVY_BARTER",
  "SCENARIOS",
  "SCOUT_JOB",
  "SCOUT_PRESTIGE_FLOOR",
  "SELA_MEDIC",
  "SIDE_DOOR_INTEL",
  "SKILLS",
  "SLOWED",
  "SNARE_TRAPPER_JOB",
  "SOLDIER_JOB",
  "SPOT",
  "STANDING_ORDERS",
  "STARTER_ARMORY",
  "STARTER_TREASURY",
  "STARTING_ROSTER",
  "STATUS_TUNING",
  "STATUS_VISUALS",
  "STAT_KEYS",
  "STEALTH",
  "STEP_SPOT",
  "STOCK_ITEMS",
  "STORIES",
  "SUBTLE_BLADE_BONUS",
  "SURVEY",
  "SURVIVALIST_JOB",
  "SWIFT",
  "TAGS",
  "THEFT",
  "THE_HOLLOW_MILL",
  "THE_RESCUE",
  "THIEF_JOB",
  "THIEVES_DEN",
  "THIEVES_GUILD_CONTACT",
  "THIEVES_GUILD_RITE",
  "TILE_HEIGHT",
  "TILE_WIDTH",
  "TRAP_FIELD",
  "TRAP_INTEL",
  "TRIAGE",
  "TRIAGE_FALLBACK",
  "TURN_THRESHOLD",
  "TileGrid",
  "UNIVERSAL_BUY",
  "UNIVERSAL_OVERWORLD_SKILLS",
  "UNIVERSAL_SKILLS",
  "UPKEEP",
  "VESSELS",
  "abilityFootprint",
  "abilityScaleBonus",
  "accrueDeclaredFaucets",
  "accrueDeployedXp",
  "accruePurseInterest",
  "accrueRp",
  "activeParty",
  "activeUnits",
  "addDelta",
  "addInfluence",
  "addItem",
  "adjacentBodies",
  "adjacentRevealedTrap",
  "advanceDyingClocksOneNight",
  "advanceFront",
  "advanceOutcome",
  "aggregate",
  "aimInRange",
  "analyzeExpedition",
  "applyBorrowEffect",
  "applyBuyEffect",
  "applyCampSkill",
  "applyCampToParty",
  "applyCharacterBoons",
  "applyDamage",
  "applyEngageInterestEffect",
  "applyGatesToGrid",
  "applyGearCondition",
  "applyGrant",
  "applyGrantEffect",
  "applyGuardPurseEffect",
  "applyHeal",
  "applyJobLevelGains",
  "applyOverworldEffect",
  "applyPatronizeEffect",
  "applyProvisionChoice",
  "applySellEffect",
  "applyStatDelta",
  "applyStatus",
  "applyStoryChoice",
  "applyTownVisit",
  "applyTriageEffect",
  "applyTriageFallbackEffect",
  "armObjectives",
  "armSkillCooldown",
  "arrivalDigest",
  "assertNever",
  "assignMember",
  "attentionCount",
  "autoTrim",
  "availableActions",
  "availableGear",
  "availableRoster",
  "availableSkills",
  "bandFor",
  "bankerBorrow",
  "bankerBorrowPreview",
  "bankerEngageInterest",
  "bankerInterestPreview",
  "bankerProtect",
  "bankerProtectPreview",
  "batchSimulate",
  "battleOutcome",
  "breakCamp",
  "breakableGates",
  "bribeChance",
  "bribeEnemy",
  "bribePrice",
  "buildAuthoredCaptives",
  "buildAuthoredEnemies",
  "buildAuthoredGates",
  "buildAuthoredGrid",
  "buildAuthoredLevers",
  "buildEnemies",
  "buildGrid",
  "buildLedger",
  "buildScenarioRun",
  "bumpCounter",
  "buyArmoryGear",
  "buyPriceFor",
  "byReadiest",
  "bypassFee",
  "bypassXp",
  "campChipLine",
  "campReadout",
  "campReadoutLine",
  "campSkillUses",
  "campSkillUsesLeft",
  "campfireRadius",
  "canAdd",
  "canAffordInfluence",
  "canAffordMaterial",
  "canAttackGate",
  "canDisarm",
  "canKeyGate",
  "canLockpickGate",
  "canPlacePlayerTrap",
  "canPullLever",
  "canRelease",
  "canSee",
  "canSeeUnit",
  "captainsJournal",
  "captureChanceAt",
  "captureEvasionFactor",
  "captureUnit",
  "caravanCapacity",
  "chebyshev",
  "checkOverworldCost",
  "chooseEventOption",
  "chooseNode",
  "chunkHp",
  "clamp",
  "clamp01",
  "clampTier",
  "clampUp",
  "clampUpMarket",
  "cleanseOne",
  "clearInjectedNodes",
  "cleaveArc",
  "clericRevive",
  "cloneOverworldEconomy",
  "combatParty",
  "commitCombatXp",
  "commitsTurn",
  "committedGearIds",
  "committedMemberIds",
  "computeDamage",
  "computeFlankBonus",
  "computeUpkeep",
  "computeVisibleTiles",
  "configureDeployClock",
  "consumeFlag",
  "cooldownRemaining",
  "countOf",
  "createCamp",
  "createCampfire",
  "createCaravan",
  "createDeployClock",
  "createFront",
  "createGuild",
  "createInventory",
  "createOverworldEconomy",
  "createPlaytestLog",
  "createRun",
  "createRunFromCaravan",
  "createRunFromExpedition",
  "createStarterGuild",
  "createUnit",
  "currentEncounter",
  "currentNode",
  "damageGate",
  "debuffs",
  "decayCounters",
  "declaredFaucetInfluence",
  "deepRest",
  "deftHandsSkim",
  "degradedMods",
  "deployActions",
  "deployForecast",
  "deployModifiers",
  "describeUnit",
  "destroyGateOnGrid",
  "disarmTrap",
  "dispatch",
  "dispatchRefusal",
  "dumpRun",
  "earlyEventForNode",
  "earn",
  "edgeDistance",
  "effectiveIntelTier",
  "effectiveMarketTier",
  "effectiveMove",
  "effectiveSpeed",
  "eligibleGrants",
  "eligiblePrestiges",
  "emptyOutcome",
  "encounterOutcome",
  "enemyCount",
  "enumerateCompletions",
  "enumeratePaths",
  "equip",
  "equipDelta",
  "equipModsSummary",
  "equippedIds",
  "evalPredicate",
  "evalPredicateRun",
  "eventChoices",
  "eventForNode",
  "eventWeightAt",
  "exchangedDamageSince",
  "exhaustionSlowSpeed",
  "exposed",
  "fatigueRisk",
  "fatigueTier",
  "fatigueTierIndex",
  "fieldedUnits",
  "fieldsJob",
  "findPath",
  "flankTiles",
  "foodFirst",
  "forecastAttack",
  "forecastEnemyAction",
  "forecastSkill",
  "forget",
  "formatDigest",
  "freeCaptive",
  "frontCaptureChance",
  "frontSpeed",
  "frontTurnStage",
  "gainRunGold",
  "gateActFor",
  "gatesOpenedByDeath",
  "gearDelta",
  "gearRefusal",
  "generateEncounter",
  "generateOverworld",
  "getAuthoredNode",
  "getCounter",
  "getDifficulty",
  "getEnemyTemplate",
  "getEquipment",
  "getExpedition",
  "getJob",
  "getMaterial",
  "getNode",
  "getQuest",
  "getScenario",
  "getSkill",
  "getStory",
  "getTag",
  "grantAbilityUseXp",
  "grantItem",
  "grantJobXp",
  "grantXp",
  "gridToScreen",
  "guarded",
  "hasActive",
  "hasBanker",
  "hasConcerns",
  "hasGear",
  "hasMember",
  "hasNoble",
  "hasNodeFlag",
  "hasPacing",
  "hasPrice",
  "hasStatus",
  "hasTag",
  "hasThief",
  "hashSeed",
  "hastened",
  "healAmount",
  "healUnit",
  "hiddenTraps",
  "hireFromPool",
  "hireMercenary",
  "hireRecruit",
  "hireRefusal",
  "immobilized",
  "inAttackRange",
  "inDangerZone",
  "inFlightCaravans",
  "inPlaceRest",
  "inPlaceRestPreview",
  "inRegion",
  "inSafeZone",
  "incrementCounter",
  "influenceTier",
  "injectAuthoredNodes",
  "injectedNodeIds",
  "intelDeployBonus",
  "intelDepthOf",
  "intelFloor",
  "isActive",
  "isAdjacent",
  "isAuthoredEncounter",
  "isBreakable",
  "isCaptured",
  "isConcealedTrap",
  "isDebuffed",
  "isDying",
  "isExhausted",
  "isFatigueTier0",
  "isFinalNode",
  "isFinalRunNode",
  "isFlanked",
  "isGoalKind",
  "isHealer",
  "isImmobilized",
  "isNodeVisible",
  "isOverworldActionEffect",
  "isPrimed",
  "isProtected",
  "isRecoverable",
  "isRunComplete",
  "isRunOver",
  "isStealthed",
  "isValidSkillTarget",
  "itemEffect",
  "jeopardyOf",
  "jobLevelOf",
  "jobPresenceSummary",
  "keyableGates",
  "keyholderOf",
  "knobDeclared",
  "listScenarios",
  "loadExpedition",
  "loadPurse",
  "loadSupply",
  "lockGateOnGrid",
  "lockGear",
  "lockpickableGates",
  "lootBandFor",
  "makeConcealedTrap",
  "makeGate",
  "makeLever",
  "makeTrap",
  "manhattan",
  "markBonus",
  "markOf",
  "markPrey",
  "marketOpenedFlag",
  "marketRank",
  "marketReadyAt",
  "marketStock",
  "marketTierBonus",
  "matchesTag",
  "medHealAmount",
  "medicalHerbs",
  "memberRefusal",
  "mercPool",
  "merchantBuy",
  "merchantBuyGold",
  "merchantPrice",
  "merchantSell",
  "moraleModifiers",
  "moraleTier",
  "moraleTierIndex",
  "mostWoundedFielded",
  "moveBudget",
  "mustGetEvent",
  "mustGetVessel",
  "nightEndGate",
  "nightlyFatigue",
  "noActionsAvailable",
  "nodeAccessible",
  "nodeEncounter",
  "nodeFee",
  "nonNegInt",
  "nudgeMorale",
  "occupiedGrid",
  "onSkillCooldown",
  "openGate",
  "openGateOnGrid",
  "openingPurseLog",
  "opposite",
  "orderOf",
  "orthoNeighbors",
  "overworldCostOf",
  "parseDump",
  "partyPresence",
  "patronize",
  "patronizePreview",
  "payTreasuryUpkeep",
  "payUpkeep",
  "pct",
  "pickRepresentatives",
  "placeParty",
  "placePlayerTrap",
  "placePlayersAutoEdge",
  "planAttack",
  "planEnemyTurn",
  "planMove",
  "playToTerminal",
  "prerequisiteProblems",
  "prestige",
  "prestigeOptions",
  "previewNode",
  "primaryJobOf",
  "primeFlag",
  "projectDossier",
  "projectForecast",
  "projectManifest",
  "protectRadiusOn",
  "pullableLevers",
  "purseFromLog",
  "purseTotalBySource",
  "rampMark",
  "rankOf",
  "reachLimit",
  "reachableFrom",
  "reachableNodes",
  "reachableTiles",
  "readActionCost",
  "readEncounter",
  "recall",
  "recalls",
  "recordCamp",
  "recordEncounter",
  "recordEventNode",
  "recordInPlaceRest",
  "recordNight",
  "recordRestNode",
  "recoverMaterials",
  "recoverStolen",
  "recruitClassify",
  "recruitToRoster",
  "recruiterOffer",
  "refillBoard",
  "refreshAuras",
  "refreshMercPool",
  "registerExpedition",
  "remember",
  "removeFromRoster",
  "removeItem",
  "removeStatus",
  "replay",
  "resetCaravan",
  "resolveAttack",
  "resolveAuthored",
  "resolveCaptured",
  "resolveDowned",
  "resolveEarlyEvent",
  "resolveEvent",
  "resolveFrontTurn",
  "resolveKnob",
  "resolveMedHeal",
  "resolveReturn",
  "resolveSkill",
  "restCostMultiplier",
  "restHeal",
  "restoreFatigue",
  "restoreRun",
  "restoreUnit",
  "retaliationDamage",
  "revealTrapsNear",
  "revertGearStamp",
  "revertStatDelta",
  "rewardBand",
  "rewardHint",
  "rollMercenary",
  "rollSkim",
  "routeCombatXp",
  "routePayoutToTreasury",
  "rpPerNight",
  "runDifficulty",
  "runEncounter",
  "runFor",
  "safeGroundRemains",
  "saleValueOf",
  "saltSeed",
  "samplePopulation",
  "satisfyUpkeepLine",
  "scoreArrival",
  "scoutedTier",
  "screenToGrid",
  "sellPrice",
  "serializeDump",
  "setCounter",
  "setNodeFlag",
  "shopBuy",
  "shopStock",
  "shoveLanding",
  "sideSeed",
  "simulateRun",
  "skillContexts",
  "skillEffectPreview",
  "skillsUnlockedBetween",
  "slotsFor",
  "slotsFree",
  "slotsOver",
  "slotsRemaining",
  "slotsUsed",
  "slowed",
  "snapshot",
  "snapshotRun",
  "snapshotUnit",
  "spend",
  "spendFatigue",
  "spendInfluence",
  "spendRp",
  "spotChance",
  "spotRadius",
  "spotWhileMoving",
  "stageEncounter",
  "stampPassives",
  "statusAmount",
  "statusVisual",
  "stealth",
  "stepDistance",
  "storyChoicePrice",
  "storyChoices",
  "storyForNode",
  "streamFor",
  "summarizePlaytest",
  "swift",
  "tailoredEarlyEventFor",
  "thiefEscapes",
  "thiefEventSkim",
  "thiefSteal",
  "threatenedTiles",
  "tickCooldowns",
  "tickSkillCooldowns",
  "tickStatuses",
  "tickUntilReady",
  "tileKey",
  "toggleUpkeepSkip",
  "tollFee",
  "trackCombatXp",
  "traverseRoute",
  "triage",
  "triageActionPreview",
  "triageFallbackRp",
  "triageHealAmount",
  "unassignMember",
  "unequip",
  "unitAbilityRows",
  "unitHasCapability",
  "unitPresence",
  "unitSkills",
  "unlockGear",
  "useOverworldSkill",
  "validateExpedition",
  "validateOverworldCost",
  "visibleNodes",
  "withDefaultGoal",
  "woundedBySeverity",
];

describe("R3 barrel surface — the core public export names are frozen (pure motion)", () => {
  it("exposes exactly the expected sorted runtime export names", () => {
    const actual = Object.keys(barrel).sort();
    expect(actual).toEqual([...EXPECTED_BARREL_SURFACE]);
  });

  it("has no duplicate export names", () => {
    const names = Object.keys(barrel);
    expect(names.length).toBe(new Set(names).size);
  });
});
